-- ============================================
-- COMMON_INQUIRY 테이블 생성
-- 문의(Inquiry) 테이블
-- ============================================

CREATE TABLE IF NOT EXISTS COMMON_INQUIRY (
    ID BIGSERIAL NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    CONTENT TEXT NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL DEFAULT 'GENERAL',
    ANSWER TEXT NULL,
    STATUS VARCHAR(50) NOT NULL DEFAULT 'PENDING',
    ANSWERED_BY VARCHAR(100) NULL,
    ANSWERED_AT TIMESTAMP NULL,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (ID),
    CONSTRAINT fk_inquiry_user FOREIGN KEY (USER_ID) REFERENCES COMMON_USER(USER_ID) ON DELETE CASCADE,
    CONSTRAINT fk_inquiry_answered_by FOREIGN KEY (ANSWERED_BY) REFERENCES COMMON_USER(USER_ID) ON DELETE SET NULL
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_common_inquiry_user_id ON COMMON_INQUIRY(USER_ID);
CREATE INDEX IF NOT EXISTS idx_common_inquiry_status ON COMMON_INQUIRY(STATUS);
CREATE INDEX IF NOT EXISTS idx_common_inquiry_category ON COMMON_INQUIRY(CATEGORY);
CREATE INDEX IF NOT EXISTS idx_common_inquiry_crt_dt ON COMMON_INQUIRY(CRT_DT);
CREATE INDEX IF NOT EXISTS idx_common_inquiry_user_status ON COMMON_INQUIRY(USER_ID, STATUS);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_inquiry_updated_at
    BEFORE UPDATE ON COMMON_INQUIRY
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_INQUIRY IS '문의';
COMMENT ON COLUMN COMMON_INQUIRY.ID IS '문의 일련번호';
COMMENT ON COLUMN COMMON_INQUIRY.USER_ID IS '문의자 ID';
COMMENT ON COLUMN COMMON_INQUIRY.TITLE IS '문의 제목';
COMMENT ON COLUMN COMMON_INQUIRY.CONTENT IS '문의 내용';
COMMENT ON COLUMN COMMON_INQUIRY.CATEGORY IS '문의 유형 (GENERAL, TECHNICAL, BUG, FEATURE, PARTNERSHIP, OTHER)';
COMMENT ON COLUMN COMMON_INQUIRY.ANSWER IS '답변 내용';
COMMENT ON COLUMN COMMON_INQUIRY.STATUS IS '문의 상태 (PENDING, ANSWERED, CLOSED)';
COMMENT ON COLUMN COMMON_INQUIRY.ANSWERED_BY IS '답변자 ID';
COMMENT ON COLUMN COMMON_INQUIRY.ANSWERED_AT IS '답변일시';
COMMENT ON COLUMN COMMON_INQUIRY.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_INQUIRY.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_INQUIRY.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_INQUIRY.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_INQUIRY.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_INQUIRY.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_INQUIRY.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_INQUIRY.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_INQUIRY.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_INQUIRY.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_INQUIRY.USE_YN IS '사용여부';
