-- ============================================
-- DDL (Data Definition Language)
-- 데이터베이스 스키마 정의
-- ============================================
-- 
-- 데이터베이스: PostgreSQL 12 이상
-- 문자셋: UTF-8 (기본)
-- 
-- 작성일: 2024-12-21
-- ============================================

-- 데이터베이스 생성 (psql에서 실행)
-- CREATE DATABASE common_db
--     WITH ENCODING 'UTF8'
--     LC_COLLATE='ko_KR.UTF-8'
--     LC_CTYPE='ko_KR.UTF-8'
--     TEMPLATE template0;

-- 스키마 설정
SET search_path TO public;

-- ============================================
-- UPD_DT 자동 업데이트 함수 생성
-- ============================================
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.UPD_DT = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ============================================
-- 1. COMMON_USER (사용자)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_USER (
    COMMON_USER_SN SERIAL NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    EML VARCHAR(255) NOT NULL,
    USERNAME VARCHAR(100) NOT NULL,
    PWD_HASH VARCHAR(255) NULL,
    NM VARCHAR(100) NULL,
    NICKNAME VARCHAR(100) NULL,
    TELNO VARCHAR(20) NULL,
    ACTV_YN BOOLEAN NOT NULL DEFAULT TRUE,
    EML_VRF_YN BOOLEAN NOT NULL DEFAULT FALSE,
    TELNO_VRF_YN BOOLEAN NOT NULL DEFAULT FALSE,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_USER_SN),
    CONSTRAINT uk_user_user_id UNIQUE (USER_ID),
    CONSTRAINT uk_user_eml UNIQUE (EML),
    CONSTRAINT uk_user_username UNIQUE (USERNAME)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_user_actv_yn ON COMMON_USER(ACTV_YN);
CREATE INDEX IF NOT EXISTS idx_user_del_yn ON COMMON_USER(DEL_YN);
CREATE INDEX IF NOT EXISTS idx_user_crt_dt ON COMMON_USER(CRT_DT);
CREATE INDEX IF NOT EXISTS idx_user_eml_vrf_yn ON COMMON_USER(EML_VRF_YN);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_user_updated_at
    BEFORE UPDATE ON COMMON_USER
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_USER IS '사용자';
COMMENT ON COLUMN COMMON_USER.COMMON_USER_SN IS '일련번호';
COMMENT ON COLUMN COMMON_USER.USER_ID IS '사용자 고유 식별자';
COMMENT ON COLUMN COMMON_USER.EML IS '이메일 주소';
COMMENT ON COLUMN COMMON_USER.USERNAME IS '사용자명';
COMMENT ON COLUMN COMMON_USER.PWD_HASH IS '비밀번호 해시값';
COMMENT ON COLUMN COMMON_USER.NM IS '이름 (실명)';
COMMENT ON COLUMN COMMON_USER.NICKNAME IS '닉네임';
COMMENT ON COLUMN COMMON_USER.TELNO IS '전화번호';
COMMENT ON COLUMN COMMON_USER.ACTV_YN IS '활성 상태';
COMMENT ON COLUMN COMMON_USER.EML_VRF_YN IS '이메일 인증 여부';
COMMENT ON COLUMN COMMON_USER.TELNO_VRF_YN IS '전화번호 인증 여부';
COMMENT ON COLUMN COMMON_USER.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_USER.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_USER.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_USER.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_USER.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_USER.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_USER.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_USER.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_USER.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_USER.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_USER.USE_YN IS '사용여부';

-- ============================================
-- 2. COMMON_OAUTH_ACCOUNT (OAuth 계정)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_OAUTH_ACCOUNT (
    COMMON_OAUTH_ACCOUNT_SN SERIAL NOT NULL,
    OAUTH_ACCOUNT_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    PROVIDER VARCHAR(50) NOT NULL,
    PROVIDER_USER_ID VARCHAR(255) NOT NULL,
    PROVIDER_EML VARCHAR(255) NULL,
    PROVIDER_USERNAME VARCHAR(100) NULL,
    ACCESS_TOKEN TEXT NULL,
    REFRESH_TOKEN TEXT NULL,
    TOKEN_EXPR_DT TIMESTAMP NULL,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_OAUTH_ACCOUNT_SN),
    CONSTRAINT uk_oauth_account_id UNIQUE (OAUTH_ACCOUNT_ID),
    CONSTRAINT uk_oauth_provider_user UNIQUE (PROVIDER, PROVIDER_USER_ID),
    CONSTRAINT fk_oauth_user_id 
        FOREIGN KEY (USER_ID) 
        REFERENCES COMMON_USER(USER_ID) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_oauth_user_id ON COMMON_OAUTH_ACCOUNT(USER_ID);
CREATE INDEX IF NOT EXISTS idx_oauth_del_yn ON COMMON_OAUTH_ACCOUNT(DEL_YN);
CREATE INDEX IF NOT EXISTS idx_oauth_provider ON COMMON_OAUTH_ACCOUNT(PROVIDER);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_oauth_account_updated_at
    BEFORE UPDATE ON COMMON_OAUTH_ACCOUNT
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_OAUTH_ACCOUNT IS 'OAuth 계정';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.COMMON_OAUTH_ACCOUNT_SN IS '일련번호';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.OAUTH_ACCOUNT_ID IS 'OAuth 계정 고유 식별자';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.USER_ID IS '사용자 ID';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.PROVIDER IS '제공자 (GOOGLE, GITHUB, KAKAO, NAVER)';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.PROVIDER_USER_ID IS '제공자에서의 사용자 ID';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.PROVIDER_EML IS '제공자에서 제공한 이메일';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.PROVIDER_USERNAME IS '제공자에서 제공한 사용자명';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.ACCESS_TOKEN IS '액세스 토큰 (암호화 저장)';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.REFRESH_TOKEN IS '리프레시 토큰 (암호화 저장)';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.TOKEN_EXPR_DT IS '토큰 만료일시';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_OAUTH_ACCOUNT.USE_YN IS '사용여부';

-- ============================================
-- 3. COMMON_ROLE (역할)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_ROLE (
    COMMON_ROLE_SN SERIAL NOT NULL,
    ROLE_ID VARCHAR(100) NOT NULL,
    ROLE_CD VARCHAR(50) NOT NULL,
    ROLE_NM VARCHAR(100) NOT NULL,
    DSC TEXT NULL,
    ACTV_YN BOOLEAN NOT NULL DEFAULT TRUE,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_ROLE_SN),
    CONSTRAINT uk_role_role_id UNIQUE (ROLE_ID),
    CONSTRAINT uk_role_role_cd UNIQUE (ROLE_CD)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_role_actv_yn ON COMMON_ROLE(ACTV_YN);
CREATE INDEX IF NOT EXISTS idx_role_del_yn ON COMMON_ROLE(DEL_YN);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_role_updated_at
    BEFORE UPDATE ON COMMON_ROLE
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_ROLE IS '역할';
COMMENT ON COLUMN COMMON_ROLE.COMMON_ROLE_SN IS '일련번호';
COMMENT ON COLUMN COMMON_ROLE.ROLE_ID IS '역할 고유 식별자';
COMMENT ON COLUMN COMMON_ROLE.ROLE_CD IS '역할 코드 (ADMIN, USER, MODERATOR)';
COMMENT ON COLUMN COMMON_ROLE.ROLE_NM IS '역할 이름';
COMMENT ON COLUMN COMMON_ROLE.DSC IS '역할 설명';
COMMENT ON COLUMN COMMON_ROLE.ACTV_YN IS '활성 상태';
COMMENT ON COLUMN COMMON_ROLE.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_ROLE.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_ROLE.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_ROLE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_ROLE.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_ROLE.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_ROLE.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_ROLE.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_ROLE.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_ROLE.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_ROLE.USE_YN IS '사용여부';

-- ============================================
-- 4. COMMON_PERMISSION (권한)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_PERMISSION (
    COMMON_PERMISSION_SN SERIAL NOT NULL,
    PERMISSION_ID VARCHAR(100) NOT NULL,
    PERMISSION_CD VARCHAR(100) NOT NULL,
    PERMISSION_NM VARCHAR(100) NOT NULL,
    DSC TEXT NULL,
    RSRC VARCHAR(50) NOT NULL,
    ACT VARCHAR(50) NOT NULL,
    ACTV_YN BOOLEAN NOT NULL DEFAULT TRUE,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_PERMISSION_SN),
    CONSTRAINT uk_permission_permission_id UNIQUE (PERMISSION_ID),
    CONSTRAINT uk_permission_permission_cd UNIQUE (PERMISSION_CD)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_permission_rsrc_act ON COMMON_PERMISSION(RSRC, ACT);
CREATE INDEX IF NOT EXISTS idx_permission_actv_yn ON COMMON_PERMISSION(ACTV_YN);
CREATE INDEX IF NOT EXISTS idx_permission_del_yn ON COMMON_PERMISSION(DEL_YN);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_permission_updated_at
    BEFORE UPDATE ON COMMON_PERMISSION
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_PERMISSION IS '권한';
COMMENT ON COLUMN COMMON_PERMISSION.COMMON_PERMISSION_SN IS '일련번호';
COMMENT ON COLUMN COMMON_PERMISSION.PERMISSION_ID IS '권한 고유 식별자';
COMMENT ON COLUMN COMMON_PERMISSION.PERMISSION_CD IS '권한 코드 (USER_CREATE, USER_UPDATE 등)';
COMMENT ON COLUMN COMMON_PERMISSION.PERMISSION_NM IS '권한 이름';
COMMENT ON COLUMN COMMON_PERMISSION.DSC IS '권한 설명';
COMMENT ON COLUMN COMMON_PERMISSION.RSRC IS '리소스 (USER, FILE, ADMIN 등)';
COMMENT ON COLUMN COMMON_PERMISSION.ACT IS '액션 (CREATE, READ, UPDATE, DELETE)';
COMMENT ON COLUMN COMMON_PERMISSION.ACTV_YN IS '활성 상태';
COMMENT ON COLUMN COMMON_PERMISSION.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_PERMISSION.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_PERMISSION.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_PERMISSION.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_PERMISSION.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_PERMISSION.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_PERMISSION.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_PERMISSION.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_PERMISSION.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_PERMISSION.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_PERMISSION.USE_YN IS '사용여부';

-- ============================================
-- 5. COMMON_ROLE_PERMISSION (역할-권한 매핑)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_ROLE_PERMISSION (
    COMMON_ROLE_PERMISSION_SN SERIAL NOT NULL,
    ROLE_PERMISSION_ID VARCHAR(100) NOT NULL,
    ROLE_ID VARCHAR(100) NOT NULL,
    PERMISSION_ID VARCHAR(100) NOT NULL,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_ROLE_PERMISSION_SN),
    CONSTRAINT uk_role_permission_id UNIQUE (ROLE_PERMISSION_ID),
    CONSTRAINT uk_role_permission_mapping UNIQUE (ROLE_ID, PERMISSION_ID),
    CONSTRAINT fk_role_permission_role_id 
        FOREIGN KEY (ROLE_ID) 
        REFERENCES COMMON_ROLE(ROLE_ID) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_role_permission_permission_id 
        FOREIGN KEY (PERMISSION_ID) 
        REFERENCES COMMON_PERMISSION(PERMISSION_ID) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_role_permission_role_id ON COMMON_ROLE_PERMISSION(ROLE_ID);
CREATE INDEX IF NOT EXISTS idx_role_permission_permission_id ON COMMON_ROLE_PERMISSION(PERMISSION_ID);
CREATE INDEX IF NOT EXISTS idx_role_permission_del_yn ON COMMON_ROLE_PERMISSION(DEL_YN);

-- 코멘트
COMMENT ON TABLE COMMON_ROLE_PERMISSION IS '역할-권한 매핑';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.COMMON_ROLE_PERMISSION_SN IS '일련번호';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.ROLE_PERMISSION_ID IS '매핑 고유 식별자';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.ROLE_ID IS '역할 ID';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.PERMISSION_ID IS '권한 ID';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_ROLE_PERMISSION.USE_YN IS '사용여부';

-- ============================================
-- 6. COMMON_USER_ROLE (사용자-역할 매핑)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_USER_ROLE (
    COMMON_USER_ROLE_SN SERIAL NOT NULL,
    USER_ROLE_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    ROLE_ID VARCHAR(100) NOT NULL,
    ASGN_BY VARCHAR(100) NULL,
    ASGN_DT TIMESTAMP NULL,
    EXPR_DT TIMESTAMP NULL,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_USER_ROLE_SN),
    CONSTRAINT uk_user_role_id UNIQUE (USER_ROLE_ID),
    CONSTRAINT uk_user_role_mapping UNIQUE (USER_ID, ROLE_ID),
    CONSTRAINT fk_user_role_user_id 
        FOREIGN KEY (USER_ID) 
        REFERENCES COMMON_USER(USER_ID) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_user_role_role_id 
        FOREIGN KEY (ROLE_ID) 
        REFERENCES COMMON_ROLE(ROLE_ID) 
        ON DELETE CASCADE
        ON UPDATE CASCADE,
    CONSTRAINT fk_user_role_asgn_by 
        FOREIGN KEY (ASGN_BY) 
        REFERENCES COMMON_USER(USER_ID) 
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_user_role_user_id ON COMMON_USER_ROLE(USER_ID);
CREATE INDEX IF NOT EXISTS idx_user_role_role_id ON COMMON_USER_ROLE(ROLE_ID);
CREATE INDEX IF NOT EXISTS idx_user_role_asgn_by ON COMMON_USER_ROLE(ASGN_BY);
CREATE INDEX IF NOT EXISTS idx_user_role_expr_dt ON COMMON_USER_ROLE(EXPR_DT);
CREATE INDEX IF NOT EXISTS idx_user_role_del_yn ON COMMON_USER_ROLE(DEL_YN);
CREATE INDEX IF NOT EXISTS idx_user_role_use_yn ON COMMON_USER_ROLE(USE_YN);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_user_role_updated_at
    BEFORE UPDATE ON COMMON_USER_ROLE
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_USER_ROLE IS '사용자-역할 매핑';
COMMENT ON COLUMN COMMON_USER_ROLE.COMMON_USER_ROLE_SN IS '일련번호';
COMMENT ON COLUMN COMMON_USER_ROLE.USER_ROLE_ID IS '매핑 고유 식별자';
COMMENT ON COLUMN COMMON_USER_ROLE.USER_ID IS '사용자 ID';
COMMENT ON COLUMN COMMON_USER_ROLE.ROLE_ID IS '역할 ID';
COMMENT ON COLUMN COMMON_USER_ROLE.ASGN_BY IS '할당한 사용자 ID';
COMMENT ON COLUMN COMMON_USER_ROLE.ASGN_DT IS '할당일시';
COMMENT ON COLUMN COMMON_USER_ROLE.EXPR_DT IS '만료일시 (NULL이면 무기한)';
COMMENT ON COLUMN COMMON_USER_ROLE.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_USER_ROLE.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_USER_ROLE.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_USER_ROLE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_USER_ROLE.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_USER_ROLE.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_USER_ROLE.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_USER_ROLE.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_USER_ROLE.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_USER_ROLE.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_USER_ROLE.USE_YN IS '사용여부';

-- ============================================
-- 7. COMMON_LANGUAGE_CONFIG (언어 설정)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_LANGUAGE_CONFIG (
    COMMON_LANGUAGE_CONFIG_SN SERIAL NOT NULL,
    LANG_CD VARCHAR(10) NOT NULL,
    LANG_NM VARCHAR(100) NOT NULL,
    DISPLAY_ORDER INTEGER NOT NULL DEFAULT 0,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    CONSTRAINT PK_COMMON_LANGUAGE_CONFIG PRIMARY KEY (COMMON_LANGUAGE_CONFIG_SN),
    CONSTRAINT UK_COMMON_LANGUAGE_CONFIG_LANG_CD UNIQUE (LANG_CD, DEL_YN)
);

COMMENT ON TABLE COMMON_LANGUAGE_CONFIG IS '언어 설정';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.COMMON_LANGUAGE_CONFIG_SN IS '언어 설정 일련번호';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.LANG_CD IS '언어 코드 (ko, en, ja, zh 등)';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.LANG_NM IS '언어 이름';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.DISPLAY_ORDER IS '표시 순서';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.USE_YN IS '사용 여부';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.DEL_DT IS '삭제 일시';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.DEL_YN IS '삭제 여부';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.CRT_DT IS '생성 일시';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.UPD_DT IS '수정 일시';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_LANGUAGE_CONFIG.UPD_BY_NM IS '수정자 이름';

-- COMMON_LANGUAGE_CONFIG 업데이트 트리거
CREATE TRIGGER TRG_COMMON_LANGUAGE_CONFIG_UPD_DT
    BEFORE UPDATE ON COMMON_LANGUAGE_CONFIG
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- ============================================
-- 8. COMMON_REFRESH_TOKEN (리프레시 토큰)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_REFRESH_TOKEN (
    COMMON_REFRESH_TOKEN_SN SERIAL NOT NULL,
    REFRESH_TOKEN_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    TOKEN_HASH VARCHAR(255) NOT NULL,
    DVC_INFO VARCHAR(255) NULL,
    IP_ADDR VARCHAR(45) NULL,
    EXPR_DT TIMESTAMP NOT NULL,
    RVK_YN BOOLEAN NOT NULL DEFAULT FALSE,
    RVK_DT TIMESTAMP NULL,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    LAST_USE_DT TIMESTAMP NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_REFRESH_TOKEN_SN),
    CONSTRAINT uk_refresh_token_id UNIQUE (REFRESH_TOKEN_ID),
    CONSTRAINT uk_refresh_token_hash UNIQUE (TOKEN_HASH),
    CONSTRAINT fk_refresh_token_user_id 
        FOREIGN KEY (USER_ID) 
        REFERENCES COMMON_USER(USER_ID) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_id ON COMMON_REFRESH_TOKEN(USER_ID);
CREATE INDEX IF NOT EXISTS idx_refresh_token_expr_dt ON COMMON_REFRESH_TOKEN(EXPR_DT);
CREATE INDEX IF NOT EXISTS idx_refresh_token_rvk_yn ON COMMON_REFRESH_TOKEN(RVK_YN);
CREATE INDEX IF NOT EXISTS idx_refresh_token_del_yn ON COMMON_REFRESH_TOKEN(DEL_YN);
CREATE INDEX IF NOT EXISTS idx_refresh_token_user_expr ON COMMON_REFRESH_TOKEN(USER_ID, EXPR_DT);

-- 코멘트
COMMENT ON TABLE COMMON_REFRESH_TOKEN IS '리프레시 토큰';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.COMMON_REFRESH_TOKEN_SN IS '일련번호';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.REFRESH_TOKEN_ID IS '토큰 고유 식별자';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.USER_ID IS '사용자 ID';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.TOKEN_HASH IS '토큰 해시값';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.DVC_INFO IS '디바이스 정보';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.IP_ADDR IS 'IP 주소 (IPv6 지원)';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.EXPR_DT IS '만료일시';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.RVK_YN IS '취소 여부';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.RVK_DT IS '취소일시';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.LAST_USE_DT IS '마지막 사용일시';
COMMENT ON COLUMN COMMON_REFRESH_TOKEN.USE_YN IS '사용여부';

-- ============================================
-- 8. COMMON_AUDIT_LOG (감사 로그)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_AUDIT_LOG (
    COMMON_AUDIT_LOG_SN BIGSERIAL NOT NULL,
    AUDIT_LOG_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NULL,
    ACT_TYP VARCHAR(50) NOT NULL,
    RSRC_TYP VARCHAR(50) NULL,
    RSRC_ID VARCHAR(100) NULL,
    OLD_VAL JSONB NULL,
    NEW_VAL JSONB NULL,
    IP_ADDR VARCHAR(45) NULL,
    USER_AGENT TEXT NULL,
    REQ_MTHD VARCHAR(10) NULL,
    REQ_PATH VARCHAR(500) NULL,
    STTS_CD INTEGER NULL,
    ERR_MSG TEXT NULL,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_AUDIT_LOG_SN),
    CONSTRAINT uk_audit_log_id UNIQUE (AUDIT_LOG_ID),
    CONSTRAINT fk_audit_log_user_id 
        FOREIGN KEY (USER_ID) 
        REFERENCES COMMON_USER(USER_ID) 
        ON DELETE SET NULL
        ON UPDATE CASCADE
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_audit_log_user_id ON COMMON_AUDIT_LOG(USER_ID);
CREATE INDEX IF NOT EXISTS idx_audit_log_user_crt_dt ON COMMON_AUDIT_LOG(USER_ID, CRT_DT);
CREATE INDEX IF NOT EXISTS idx_audit_log_act_crt_dt ON COMMON_AUDIT_LOG(ACT_TYP, CRT_DT);
CREATE INDEX IF NOT EXISTS idx_audit_log_rsrc ON COMMON_AUDIT_LOG(RSRC_TYP, RSRC_ID);
CREATE INDEX IF NOT EXISTS idx_audit_log_crt_dt ON COMMON_AUDIT_LOG(CRT_DT);
CREATE INDEX IF NOT EXISTS idx_audit_log_act_typ ON COMMON_AUDIT_LOG(ACT_TYP);
CREATE INDEX IF NOT EXISTS idx_audit_log_rsrc_typ ON COMMON_AUDIT_LOG(RSRC_TYP);
CREATE INDEX IF NOT EXISTS idx_audit_log_del_yn ON COMMON_AUDIT_LOG(DEL_YN);

-- 파티셔닝 (연도별) - PostgreSQL 10+ 지원
-- CREATE TABLE COMMON_AUDIT_LOG_2024 PARTITION OF COMMON_AUDIT_LOG
--     FOR VALUES FROM ('2024-01-01') TO ('2025-01-01');
-- CREATE TABLE COMMON_AUDIT_LOG_2025 PARTITION OF COMMON_AUDIT_LOG
--     FOR VALUES FROM ('2025-01-01') TO ('2026-01-01');

-- 코멘트
COMMENT ON TABLE COMMON_AUDIT_LOG IS '감사 로그';
COMMENT ON COLUMN COMMON_AUDIT_LOG.COMMON_AUDIT_LOG_SN IS '일련번호';
COMMENT ON COLUMN COMMON_AUDIT_LOG.AUDIT_LOG_ID IS '로그 고유 식별자';
COMMENT ON COLUMN COMMON_AUDIT_LOG.USER_ID IS '사용자 ID (NULL 가능)';
COMMENT ON COLUMN COMMON_AUDIT_LOG.ACT_TYP IS '액션 타입 (LOGIN, LOGOUT, CREATE, UPDATE, DELETE, API_CALL)';
COMMENT ON COLUMN COMMON_AUDIT_LOG.RSRC_TYP IS '리소스 타입 (USER, FILE, ROLE 등)';
COMMENT ON COLUMN COMMON_AUDIT_LOG.RSRC_ID IS '리소스 ID';
COMMENT ON COLUMN COMMON_AUDIT_LOG.OLD_VAL IS '변경 전 값 (JSON 형식)';
COMMENT ON COLUMN COMMON_AUDIT_LOG.NEW_VAL IS '변경 후 값 (JSON 형식)';
COMMENT ON COLUMN COMMON_AUDIT_LOG.IP_ADDR IS 'IP 주소';
COMMENT ON COLUMN COMMON_AUDIT_LOG.USER_AGENT IS 'User Agent';
COMMENT ON COLUMN COMMON_AUDIT_LOG.REQ_MTHD IS 'HTTP 메서드 (GET, POST, PUT, DELETE)';
COMMENT ON COLUMN COMMON_AUDIT_LOG.REQ_PATH IS '요청 경로';
COMMENT ON COLUMN COMMON_AUDIT_LOG.STTS_CD IS 'HTTP 상태 코드';
COMMENT ON COLUMN COMMON_AUDIT_LOG.ERR_MSG IS '에러 메시지';
COMMENT ON COLUMN COMMON_AUDIT_LOG.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_AUDIT_LOG.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_AUDIT_LOG.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_AUDIT_LOG.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_AUDIT_LOG.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_AUDIT_LOG.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_AUDIT_LOG.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_AUDIT_LOG.USE_YN IS '사용여부';

-- ============================================
-- 9. COMMON_FILE (파일)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_FILE (
    COMMON_FILE_SN SERIAL NOT NULL,
    FILE_ID VARCHAR(100) NOT NULL,
    USER_ID VARCHAR(100) NOT NULL,
    FILE_NM VARCHAR(255) NOT NULL,
    FILE_PATH VARCHAR(500) NOT NULL,
    FILE_SZ BIGINT NOT NULL,
    MIME_TYP VARCHAR(100) NULL,
    FILE_EXT VARCHAR(10) NULL,
    STG_TYP VARCHAR(20) NOT NULL DEFAULT 'LOCAL',
    PUB_YN BOOLEAN NOT NULL DEFAULT FALSE,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_FILE_SN),
    CONSTRAINT uk_file_file_id UNIQUE (FILE_ID),
    CONSTRAINT fk_file_user_id 
        FOREIGN KEY (USER_ID) 
        REFERENCES COMMON_USER(USER_ID) 
        ON DELETE CASCADE
        ON UPDATE CASCADE
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_file_user_id ON COMMON_FILE(USER_ID);
CREATE INDEX IF NOT EXISTS idx_file_file_ext ON COMMON_FILE(FILE_EXT);
CREATE INDEX IF NOT EXISTS idx_file_mime_typ ON COMMON_FILE(MIME_TYP);
CREATE INDEX IF NOT EXISTS idx_file_stg_typ ON COMMON_FILE(STG_TYP);
CREATE INDEX IF NOT EXISTS idx_file_pub_yn ON COMMON_FILE(PUB_YN);
CREATE INDEX IF NOT EXISTS idx_file_del_yn ON COMMON_FILE(DEL_YN);
CREATE INDEX IF NOT EXISTS idx_file_crt_dt ON COMMON_FILE(CRT_DT);
CREATE INDEX IF NOT EXISTS idx_file_user_crt ON COMMON_FILE(USER_ID, CRT_DT);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_file_updated_at
    BEFORE UPDATE ON COMMON_FILE
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_FILE IS '파일';
COMMENT ON COLUMN COMMON_FILE.COMMON_FILE_SN IS '일련번호';
COMMENT ON COLUMN COMMON_FILE.FILE_ID IS '파일 고유 식별자';
COMMENT ON COLUMN COMMON_FILE.USER_ID IS '업로드한 사용자 ID';
COMMENT ON COLUMN COMMON_FILE.FILE_NM IS '원본 파일명';
COMMENT ON COLUMN COMMON_FILE.FILE_PATH IS '저장 경로';
COMMENT ON COLUMN COMMON_FILE.FILE_SZ IS '파일 크기 (바이트)';
COMMENT ON COLUMN COMMON_FILE.MIME_TYP IS 'MIME 타입';
COMMENT ON COLUMN COMMON_FILE.FILE_EXT IS '파일 확장자';
COMMENT ON COLUMN COMMON_FILE.STG_TYP IS '저장소 타입 (LOCAL, S3 등)';
COMMENT ON COLUMN COMMON_FILE.PUB_YN IS '공개 여부';
COMMENT ON COLUMN COMMON_FILE.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_FILE.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_FILE.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_FILE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_FILE.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_FILE.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_FILE.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_FILE.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_FILE.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_FILE.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_FILE.USE_YN IS '사용여부';

-- ============================================
-- 10. COMMON_LOCALE (다국어)
-- ============================================
CREATE TABLE IF NOT EXISTS COMMON_LOCALE (
    COMMON_LOCALE_SN SERIAL NOT NULL,
    LOCALE_ID VARCHAR(100) NOT NULL,
    LANG_CD VARCHAR(10) NOT NULL,
    RSRC_TYP VARCHAR(50) NOT NULL,
    RSRC_KEY VARCHAR(255) NOT NULL,
    RSRC_VAL TEXT NOT NULL,
    DEL_DT TIMESTAMP NULL,
    DEL_BY VARCHAR(100) NULL,
    DEL_BY_NM VARCHAR(100) NULL,
    DEL_YN BOOLEAN NOT NULL DEFAULT FALSE,
    CRT_DT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CRT_BY VARCHAR(100) NULL,
    CRT_BY_NM VARCHAR(100) NULL,
    UPD_DT TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    UPD_BY VARCHAR(100) NULL,
    UPD_BY_NM VARCHAR(100) NULL,
    USE_YN BOOLEAN NOT NULL DEFAULT TRUE,
    PRIMARY KEY (COMMON_LOCALE_SN),
    CONSTRAINT uk_locale_locale_id UNIQUE (LOCALE_ID),
    CONSTRAINT uk_locale_key UNIQUE (LANG_CD, RSRC_TYP, RSRC_KEY)
);

-- 인덱스 생성
CREATE INDEX IF NOT EXISTS idx_locale_lang_cd ON COMMON_LOCALE(LANG_CD);
CREATE INDEX IF NOT EXISTS idx_locale_rsrc_typ ON COMMON_LOCALE(RSRC_TYP);
CREATE INDEX IF NOT EXISTS idx_locale_del_yn ON COMMON_LOCALE(DEL_YN);
CREATE INDEX IF NOT EXISTS idx_locale_use_yn ON COMMON_LOCALE(USE_YN);

-- UPD_DT 자동 업데이트 트리거
CREATE TRIGGER update_common_locale_updated_at
    BEFORE UPDATE ON COMMON_LOCALE
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- 코멘트
COMMENT ON TABLE COMMON_LOCALE IS '다국어';
COMMENT ON COLUMN COMMON_LOCALE.COMMON_LOCALE_SN IS '일련번호';
COMMENT ON COLUMN COMMON_LOCALE.LOCALE_ID IS '번역 고유 식별자';
COMMENT ON COLUMN COMMON_LOCALE.LANG_CD IS '언어 코드 (ko, en, ja 등)';
COMMENT ON COLUMN COMMON_LOCALE.RSRC_TYP IS '리소스 타입 (LABEL, MESSAGE, ERROR 등)';
COMMENT ON COLUMN COMMON_LOCALE.RSRC_KEY IS '리소스 키';
COMMENT ON COLUMN COMMON_LOCALE.RSRC_VAL IS '번역된 값';
COMMENT ON COLUMN COMMON_LOCALE.DEL_DT IS '삭제일시 (소프트 삭제)';
COMMENT ON COLUMN COMMON_LOCALE.DEL_BY IS '삭제자 ID';
COMMENT ON COLUMN COMMON_LOCALE.DEL_BY_NM IS '삭제자 이름';
COMMENT ON COLUMN COMMON_LOCALE.DEL_YN IS '삭제여부';
COMMENT ON COLUMN COMMON_LOCALE.CRT_DT IS '생성일시';
COMMENT ON COLUMN COMMON_LOCALE.CRT_BY IS '생성자 ID';
COMMENT ON COLUMN COMMON_LOCALE.CRT_BY_NM IS '생성자 이름';
COMMENT ON COLUMN COMMON_LOCALE.UPD_DT IS '수정일시';
COMMENT ON COLUMN COMMON_LOCALE.UPD_BY IS '수정자 ID';
COMMENT ON COLUMN COMMON_LOCALE.UPD_BY_NM IS '수정자 이름';
COMMENT ON COLUMN COMMON_LOCALE.USE_YN IS '사용여부';

-- ============================================
-- 테이블 생성 완료
-- ============================================
